version: '3.7'
services:
  json-server:
    image: srank123/json-server:0.1.0
    build:
      context: ./json-server
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  postman:
    image: srank123/postman:0.1.0
    build:
      context: ./newman
      dockerfile: ./Dockerfile
    command: |
      run demo.postman_collection.json
      -e environment.postman_environment.json
      -r cli,htmlextra --reporter-htmlextra-export reports/report.html
      --env-var "HOST=host.docker.internal:3000"
    volumes:
      - ./newman/reports:/etc/newman/reports